import test from 'node:test';
import assert from 'node:assert/strict';
import { preparePreview, validatePrepareEnvironment, PREVIEW_PREPARE_CONFIRMATION } from '../scripts/prepare-preview.ts';
const direct = 'postgresql://synthetic:owner-entered-secret@ep-odd-paper-azxfykgo.c-3.ap-southeast-1.aws.neon.tech/vps_tr_mock?sslmode=require';
const env = { APP_ENV: 'preview', VERCEL_ENV: 'preview', DATABASE_URL: direct, DIRECT_URL: direct, PREVIEW_PREPARE_ONCE: PREVIEW_PREPARE_CONFIRMATION, PREVIEW_ADMIN_PASSWORD: 'synthetic-long-password-for-dry-tests' };
function harness(existing = false) { const calls = []; const client = { user: { async findUnique() { calls.push('lookup-admin'); return existing ? { id: 1 } : null; }, async create({ data }) { calls.push('create-admin'); assert.equal(data.password, 'hash-only'); assert.equal(data.employeeId, 'DEMO_ADMIN'); assert.equal(data.role, 'ADMIN'); } }, workCenter: { async findUnique() { return { id: 2 }; } }, branch: { async findUnique() { return { id: 5 }; } }, async $disconnect() { calls.push('disconnect'); } }; const ports = { async migrate() { calls.push('migrate'); }, async seed({ args }) { calls.push(args?.includes('--lookup-only') ? 'lookup-seed' : 'full-seed'); return { workCenters: 13, branches: 66, transformers: 30, calendarExceptions: 4, outageRequests: 50, lookupOnly: Boolean(args) }; }, async client() { calls.push('client'); return client; }, async hashPassword(password) { assert.equal(password, env.PREVIEW_ADMIN_PASSWORD); calls.push('hash'); return 'hash-only'; } }; return { calls, ports }; }
test('preparation refuses wrong/missing opt-in and target before connection/subprocess', async () => { for (const bad of [{ APP_ENV: undefined }, { VERCEL_ENV: 'production' }, { PREVIEW_PREPARE_ONCE: undefined }, { DIRECT_URL: direct.replace('vps_tr_mock', 'production') }, { DATABASE_URL: direct.replace('ep-odd-paper-azxfykgo.c-3.ap-southeast-1.aws.neon.tech', 'unknown.example') }, { DIRECT_URL: direct.replace('azxfykgo.c-3', 'azxfykgo-pooler.c-3') }, { PREVIEW_ADMIN_PASSWORD: 'short' }]) {
    const { calls, ports } = harness();
    await assert.rejects(preparePreview({ ...env, ...bad }, ports));
    assert.deepEqual(calls, []);
} });
test('preparation orders verified migrations, lookup seed, private password hash, account and full seed', async () => { const { calls, ports } = harness(); const result = await preparePreview(env, ports); assert.equal(result.createdAdmin, true); assert.deepEqual(calls, ['migrate', 'lookup-seed', 'client', 'lookup-admin', 'hash', 'create-admin', 'disconnect', 'full-seed']); assert.ok(!JSON.stringify(result).includes(env.PREVIEW_ADMIN_PASSWORD)); });
test('repeated preparation never hashes/resets an existing synthetic account', async () => { const { calls, ports } = harness(true); const result = await preparePreview(env, ports); assert.equal(result.createdAdmin, false); assert.ok(!calls.includes('create-admin')); assert.ok(!calls.includes('hash')); });
test('invalid target errors do not disclose URL credentials', () => { assert.throws(() => validatePrepareEnvironment({ ...env, DIRECT_URL: direct.replace('vps_tr_mock', 'production') }), (error) => !error.message.includes('owner-entered-secret') && !error.message.includes('synthetic:')); });
